apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: services
  labels:
    {{- include "ingress-setup.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress }}
    {{- toYaml .annotations | nindent 4 }}
    {{- include "ingress-setup.certManagerAnnotation" $ | nindent 4 }}
    {{- if .keycloak.allowedSourceRanges }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .keycloak.allowedSourceRanges | join "," | quote }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: keycloak
                port:
                  number: 80
